// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_batch`, `chunk_schema`, `column`, `delete_where`, `escape_literal`, `rows_from_batch`, `rt`, `validate_vector`, `vector_dim`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NativeChunkStore>>
abstract class NativeChunkStore implements RustOpaqueInterface {
  /// Appends `rows` with their flattened `vectors` in a single transaction.
  Future<void> add({
    required List<RustChunkRow> rows,
    required List<double> vectors,
  });

  /// Compacts fragments and prunes superseded versions.
  ///
  /// Every append and delete creates a new dataset version, and Lance keeps
  /// them until told otherwise, so this runs after each import.
  Future<void> compact();

  Future<int> count();

  /// Removes every row belonging to one document.
  Future<void> deleteDoc({required String docId});

  Future<int> dim();

  /// Distinct document ids currently in the table.
  Future<List<String>> docIds();

  /// Opens the store at `path`, creating the table when it does not exist.
  ///
  /// A table whose vector width disagrees with `dim` is an error rather than
  /// a silent reset: the collection's embedding profile changed and the data
  /// has to be rebuilt.
  static Future<NativeChunkStore> open({
    required String path,
    required int dim,
  }) => RustLib.instance.api.crateApiLanceStoreNativeChunkStoreOpen(
    path: path,
    dim: dim,
  );

  /// Non-vector scan of one page of one document, ordered by chunk ordinal.
  Future<List<RustChunkRow>> pageChunks({
    required String docId,
    required int page,
    required int limit,
  });

  /// Removes rows whose document is not in `doc_ids`, returning the number of
  /// documents dropped. This is the orphan sweep that replaces the old
  /// dirty/clean index-state protocol.
  ///
  /// Nothing is written when there is nothing stale — every write would
  /// otherwise append a dataset version on each app start.
  Future<int> retainDocs({required List<String> docIds});

  /// Exact cosine search. Embeddings are L2-normalized by the caller, so the
  /// returned score is the cosine similarity.
  Future<List<RustChunkHit>> search({
    required List<double> query,
    required int k,
  });
}

/// A search hit: the row plus its cosine similarity (higher is better).
class RustChunkHit {
  final RustChunkRow row;
  final double score;

  const RustChunkHit({required this.row, required this.score});

  @override
  int get hashCode => row.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustChunkHit &&
          runtimeType == other.runtimeType &&
          row == other.row &&
          score == other.score;
}

/// One indexed chunk. Mirrors the persisted columns, minus the vector.
class RustChunkRow {
  final String chunkId;
  final String docId;
  final int page;
  final int ordinal;
  final String section;
  final int startChar;
  final int endChar;
  final String text;

  const RustChunkRow({
    required this.chunkId,
    required this.docId,
    required this.page,
    required this.ordinal,
    required this.section,
    required this.startChar,
    required this.endChar,
    required this.text,
  });

  @override
  int get hashCode =>
      chunkId.hashCode ^
      docId.hashCode ^
      page.hashCode ^
      ordinal.hashCode ^
      section.hashCode ^
      startChar.hashCode ^
      endChar.hashCode ^
      text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustChunkRow &&
          runtimeType == other.runtimeType &&
          chunkId == other.chunkId &&
          docId == other.docId &&
          page == other.page &&
          ordinal == other.ordinal &&
          section == other.section &&
          startChar == other.startChar &&
          endChar == other.endChar &&
          text == other.text;
}
