// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blank_pixel`, `color_space_components`, `decode_image`, `dict_u32`, `filter_names`, `is_image`, `page_image_xobjects`, `resolve`

/// Extracts every raster image at least `min_width` x `min_height` and returns
/// the document with those images blanked out.
///
/// The size floor matters: papers are full of rule lines, logos, bullet glyphs
/// and inline math bitmaps, and embedding those wastes tokens for no retrieval
/// value. Images below the floor are left in the PDF untouched.
Future<StrippedPdf> extractAndStripImages({
  required String pdfPath,
  required int minWidth,
  required int minHeight,
}) => RustLib.instance.api.crateApiPdfImagesExtractAndStripImages(
  pdfPath: pdfPath,
  minWidth: minWidth,
  minHeight: minHeight,
);

/// One raster image recovered from the PDF.
class ExtractedImage {
  /// 1-based page the image is drawn on. When an image is shared by several
  /// pages this is the first one that referenced it.
  final int page;

  /// Position of this image within its page, in resource order.
  final int indexOnPage;

  /// The XObject's resource name, e.g. `Im1`.
  final String name;
  final int width;
  final int height;

  /// `image/jpeg` or `image/png`.
  final String mediaType;
  final Uint8List bytes;

  const ExtractedImage({
    required this.page,
    required this.indexOnPage,
    required this.name,
    required this.width,
    required this.height,
    required this.mediaType,
    required this.bytes,
  });

  @override
  int get hashCode =>
      page.hashCode ^
      indexOnPage.hashCode ^
      name.hashCode ^
      width.hashCode ^
      height.hashCode ^
      mediaType.hashCode ^
      bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractedImage &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          indexOnPage == other.indexOnPage &&
          name == other.name &&
          width == other.width &&
          height == other.height &&
          mediaType == other.mediaType &&
          bytes == other.bytes;
}

/// The result of one strip pass.
class StrippedPdf {
  /// The image-free PDF, ready to be base64'd and uploaded.
  final Uint8List pdf;
  final List<ExtractedImage> images;
  final int pageCount;

  /// Byte size of the original file, for logging the saving.
  final int originalBytes;

  /// Images that were found but could not be decoded, and so were left in
  /// the PDF for the OCR pass to deal with.
  final int skipped;

  const StrippedPdf({
    required this.pdf,
    required this.images,
    required this.pageCount,
    required this.originalBytes,
    required this.skipped,
  });

  @override
  int get hashCode =>
      pdf.hashCode ^
      images.hashCode ^
      pageCount.hashCode ^
      originalBytes.hashCode ^
      skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StrippedPdf &&
          runtimeType == other.runtimeType &&
          pdf == other.pdf &&
          images == other.images &&
          pageCount == other.pageCount &&
          originalBytes == other.originalBytes &&
          skipped == other.skipped;
}
