// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

Future<RustPdfProcessedResult> parsePdf({
  required String filePath,
  required String documentId,
  String? fallbackTitle,
}) => RustLib.instance.api.crateApiPdfParserParsePdf(
  filePath: filePath,
  documentId: documentId,
  fallbackTitle: fallbackTitle,
);

Future<List<RustPaperChunk>> chunkText({
  required String pageText,
  required int pageNum,
  required String documentId,
  required String section,
  required int startOrdinal,
}) => RustLib.instance.api.crateApiPdfParserChunkText(
  pageText: pageText,
  pageNum: pageNum,
  documentId: documentId,
  section: section,
  startOrdinal: startOrdinal,
);

class RustPaperChunk {
  final String id;
  final int vectorId;
  final int page;
  final int ordinal;
  final String section;
  final int startChar;
  final int endChar;
  final String text;

  const RustPaperChunk({
    required this.id,
    required this.vectorId,
    required this.page,
    required this.ordinal,
    required this.section,
    required this.startChar,
    required this.endChar,
    required this.text,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      vectorId.hashCode ^
      page.hashCode ^
      ordinal.hashCode ^
      section.hashCode ^
      startChar.hashCode ^
      endChar.hashCode ^
      text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustPaperChunk &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          vectorId == other.vectorId &&
          page == other.page &&
          ordinal == other.ordinal &&
          section == other.section &&
          startChar == other.startChar &&
          endChar == other.endChar &&
          text == other.text;
}

class RustPdfProcessedResult {
  final String title;
  final int pageCount;
  final List<RustPaperChunk> chunks;
  final Int32List emptyPages;
  final String pdfType;
  final Int32List needsOcrPages;

  const RustPdfProcessedResult({
    required this.title,
    required this.pageCount,
    required this.chunks,
    required this.emptyPages,
    required this.pdfType,
    required this.needsOcrPages,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      pageCount.hashCode ^
      chunks.hashCode ^
      emptyPages.hashCode ^
      pdfType.hashCode ^
      needsOcrPages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustPdfProcessedResult &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          pageCount == other.pageCount &&
          chunks == other.chunks &&
          emptyPages == other.emptyPages &&
          pdfType == other.pdfType &&
          needsOcrPages == other.needsOcrPages;
}
