// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `norm`, `validate_vector`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NativeVectorIndex>>
abstract class NativeVectorIndex implements RustOpaqueInterface {
  Future<void> addBatch({
    required List<int> ids,
    required List<double> vectors,
    required int dim,
  });

  Future<int> dim();

  Future<int> len();

  static Future<NativeVectorIndex> load({required String path}) =>
      RustLib.instance.api.crateApiVectorIndexNativeVectorIndexLoad(path: path);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// A `dim` of zero defers the dimension until the first `add_batch`.
  static Future<NativeVectorIndex> newInstance({
    required int dim,
    required int bitWidth,
  }) => RustLib.instance.api.crateApiVectorIndexNativeVectorIndexNew(
    dim: dim,
    bitWidth: bitWidth,
  );

  Future<bool> remove({required int id});

  Future<List<RustSearchResult>> search({
    required List<double> query,
    required int k,
    List<int>? allowlist,
  });

  Future<void> write({required String path});
}

class RustSearchResult {
  final int vectorId;
  final double score;

  const RustSearchResult({required this.vectorId, required this.score});

  @override
  int get hashCode => vectorId.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustSearchResult &&
          runtimeType == other.runtimeType &&
          vectorId == other.vectorId &&
          score == other.score;
}
