// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/lance_store.dart';
import 'api/pdf_parser.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -2114872438;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'lab_05_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiLanceStoreNativeChunkStoreAdd({
    required NativeChunkStore that,
    required List<RustChunkRow> rows,
    required List<double> vectors,
  });

  Future<void> crateApiLanceStoreNativeChunkStoreCompact({
    required NativeChunkStore that,
  });

  Future<int> crateApiLanceStoreNativeChunkStoreCount({
    required NativeChunkStore that,
  });

  Future<void> crateApiLanceStoreNativeChunkStoreDeleteDoc({
    required NativeChunkStore that,
    required String docId,
  });

  Future<int> crateApiLanceStoreNativeChunkStoreDim({
    required NativeChunkStore that,
  });

  Future<List<String>> crateApiLanceStoreNativeChunkStoreDocIds({
    required NativeChunkStore that,
  });

  Future<NativeChunkStore> crateApiLanceStoreNativeChunkStoreOpen({
    required String path,
    required int dim,
  });

  Future<List<RustChunkRow>> crateApiLanceStoreNativeChunkStorePageChunks({
    required NativeChunkStore that,
    required String docId,
    required int page,
    required int limit,
  });

  Future<int> crateApiLanceStoreNativeChunkStoreRetainDocs({
    required NativeChunkStore that,
    required List<String> docIds,
  });

  Future<List<RustChunkHit>> crateApiLanceStoreNativeChunkStoreSearch({
    required NativeChunkStore that,
    required List<double> query,
    required int k,
  });

  Future<List<RustPaperChunk>> crateApiPdfParserChunkText({
    required String pageText,
    required int pageNum,
    required String documentId,
    required String section,
    required int startOrdinal,
  });

  Future<void> crateApiInitApp();

  Future<RustPdfProcessedResult> crateApiPdfParserParsePdf({
    required String filePath,
    required String documentId,
    String? fallbackTitle,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NativeChunkStore;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NativeChunkStore;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NativeChunkStorePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiLanceStoreNativeChunkStoreAdd({
    required NativeChunkStore that,
    required List<RustChunkRow> rows,
    required List<double> vectors,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
            that,
            serializer,
          );
          sse_encode_list_rust_chunk_row(rows, serializer);
          sse_encode_list_prim_f_32_loose(vectors, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLanceStoreNativeChunkStoreAddConstMeta,
        argValues: [that, rows, vectors],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceStoreNativeChunkStoreAddConstMeta =>
      const TaskConstMeta(
        debugName: "NativeChunkStore_add",
        argNames: ["that", "rows", "vectors"],
      );

  @override
  Future<void> crateApiLanceStoreNativeChunkStoreCompact({
    required NativeChunkStore that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLanceStoreNativeChunkStoreCompactConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceStoreNativeChunkStoreCompactConstMeta =>
      const TaskConstMeta(
        debugName: "NativeChunkStore_compact",
        argNames: ["that"],
      );

  @override
  Future<int> crateApiLanceStoreNativeChunkStoreCount({
    required NativeChunkStore that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_CastedPrimitive_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLanceStoreNativeChunkStoreCountConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceStoreNativeChunkStoreCountConstMeta =>
      const TaskConstMeta(
        debugName: "NativeChunkStore_count",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiLanceStoreNativeChunkStoreDeleteDoc({
    required NativeChunkStore that,
    required String docId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
            that,
            serializer,
          );
          sse_encode_String(docId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLanceStoreNativeChunkStoreDeleteDocConstMeta,
        argValues: [that, docId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceStoreNativeChunkStoreDeleteDocConstMeta =>
      const TaskConstMeta(
        debugName: "NativeChunkStore_delete_doc",
        argNames: ["that", "docId"],
      );

  @override
  Future<int> crateApiLanceStoreNativeChunkStoreDim({
    required NativeChunkStore that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_CastedPrimitive_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLanceStoreNativeChunkStoreDimConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceStoreNativeChunkStoreDimConstMeta =>
      const TaskConstMeta(
        debugName: "NativeChunkStore_dim",
        argNames: ["that"],
      );

  @override
  Future<List<String>> crateApiLanceStoreNativeChunkStoreDocIds({
    required NativeChunkStore that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLanceStoreNativeChunkStoreDocIdsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceStoreNativeChunkStoreDocIdsConstMeta =>
      const TaskConstMeta(
        debugName: "NativeChunkStore_doc_ids",
        argNames: ["that"],
      );

  @override
  Future<NativeChunkStore> crateApiLanceStoreNativeChunkStoreOpen({
    required String path,
    required int dim,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_CastedPrimitive_usize(dim, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLanceStoreNativeChunkStoreOpenConstMeta,
        argValues: [path, dim],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceStoreNativeChunkStoreOpenConstMeta =>
      const TaskConstMeta(
        debugName: "NativeChunkStore_open",
        argNames: ["path", "dim"],
      );

  @override
  Future<List<RustChunkRow>> crateApiLanceStoreNativeChunkStorePageChunks({
    required NativeChunkStore that,
    required String docId,
    required int page,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
            that,
            serializer,
          );
          sse_encode_String(docId, serializer);
          sse_encode_i_32(page, serializer);
          sse_encode_CastedPrimitive_usize(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rust_chunk_row,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLanceStoreNativeChunkStorePageChunksConstMeta,
        argValues: [that, docId, page, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceStoreNativeChunkStorePageChunksConstMeta =>
      const TaskConstMeta(
        debugName: "NativeChunkStore_page_chunks",
        argNames: ["that", "docId", "page", "limit"],
      );

  @override
  Future<int> crateApiLanceStoreNativeChunkStoreRetainDocs({
    required NativeChunkStore that,
    required List<String> docIds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
            that,
            serializer,
          );
          sse_encode_list_String(docIds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_CastedPrimitive_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLanceStoreNativeChunkStoreRetainDocsConstMeta,
        argValues: [that, docIds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceStoreNativeChunkStoreRetainDocsConstMeta =>
      const TaskConstMeta(
        debugName: "NativeChunkStore_retain_docs",
        argNames: ["that", "docIds"],
      );

  @override
  Future<List<RustChunkHit>> crateApiLanceStoreNativeChunkStoreSearch({
    required NativeChunkStore that,
    required List<double> query,
    required int k,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
            that,
            serializer,
          );
          sse_encode_list_prim_f_32_loose(query, serializer);
          sse_encode_CastedPrimitive_usize(k, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rust_chunk_hit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLanceStoreNativeChunkStoreSearchConstMeta,
        argValues: [that, query, k],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLanceStoreNativeChunkStoreSearchConstMeta =>
      const TaskConstMeta(
        debugName: "NativeChunkStore_search",
        argNames: ["that", "query", "k"],
      );

  @override
  Future<List<RustPaperChunk>> crateApiPdfParserChunkText({
    required String pageText,
    required int pageNum,
    required String documentId,
    required String section,
    required int startOrdinal,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pageText, serializer);
          sse_encode_i_32(pageNum, serializer);
          sse_encode_String(documentId, serializer);
          sse_encode_String(section, serializer);
          sse_encode_i_32(startOrdinal, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rust_paper_chunk,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPdfParserChunkTextConstMeta,
        argValues: [pageText, pageNum, documentId, section, startOrdinal],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfParserChunkTextConstMeta => const TaskConstMeta(
    debugName: "chunk_text",
    argNames: ["pageText", "pageNum", "documentId", "section", "startOrdinal"],
  );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<RustPdfProcessedResult> crateApiPdfParserParsePdf({
    required String filePath,
    required String documentId,
    String? fallbackTitle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          sse_encode_String(documentId, serializer);
          sse_encode_opt_String(fallbackTitle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rust_pdf_processed_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPdfParserParsePdfConstMeta,
        argValues: [filePath, documentId, fallbackTitle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfParserParsePdfConstMeta => const TaskConstMeta(
    debugName: "parse_pdf",
    argNames: ["filePath", "documentId", "fallbackTitle"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NativeChunkStore => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NativeChunkStore => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore;

  @protected
  NativeChunkStore
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativeChunkStoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NativeChunkStore
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativeChunkStoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  int dco_decode_CastedPrimitive_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  NativeChunkStore
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativeChunkStoreImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RustChunkHit> dco_decode_list_rust_chunk_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_chunk_hit).toList();
  }

  @protected
  List<RustChunkRow> dco_decode_list_rust_chunk_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_chunk_row).toList();
  }

  @protected
  List<RustPaperChunk> dco_decode_list_rust_paper_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_paper_chunk).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RustChunkHit dco_decode_rust_chunk_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustChunkHit(
      row: dco_decode_rust_chunk_row(arr[0]),
      score: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  RustChunkRow dco_decode_rust_chunk_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return RustChunkRow(
      chunkId: dco_decode_String(arr[0]),
      docId: dco_decode_String(arr[1]),
      page: dco_decode_i_32(arr[2]),
      ordinal: dco_decode_i_32(arr[3]),
      section: dco_decode_String(arr[4]),
      startChar: dco_decode_i_32(arr[5]),
      endChar: dco_decode_i_32(arr[6]),
      text: dco_decode_String(arr[7]),
    );
  }

  @protected
  RustPaperChunk dco_decode_rust_paper_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return RustPaperChunk(
      id: dco_decode_String(arr[0]),
      page: dco_decode_i_32(arr[1]),
      ordinal: dco_decode_i_32(arr[2]),
      section: dco_decode_String(arr[3]),
      startChar: dco_decode_i_32(arr[4]),
      endChar: dco_decode_i_32(arr[5]),
      text: dco_decode_String(arr[6]),
    );
  }

  @protected
  RustPdfProcessedResult dco_decode_rust_pdf_processed_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RustPdfProcessedResult(
      title: dco_decode_String(arr[0]),
      pageCount: dco_decode_i_32(arr[1]),
      chunks: dco_decode_list_rust_paper_chunk(arr[2]),
      emptyPages: dco_decode_list_prim_i_32_strict(arr[3]),
      pdfType: dco_decode_String(arr[4]),
      needsOcrPages: dco_decode_list_prim_i_32_strict(arr[5]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  NativeChunkStore
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NativeChunkStoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NativeChunkStore
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NativeChunkStoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  int sse_decode_CastedPrimitive_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_usize(deserializer);
    return inner.toInt();
  }

  @protected
  NativeChunkStore
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NativeChunkStoreImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RustChunkHit> sse_decode_list_rust_chunk_hit(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustChunkHit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_chunk_hit(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustChunkRow> sse_decode_list_rust_chunk_row(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustChunkRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_chunk_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<RustPaperChunk> sse_decode_list_rust_paper_chunk(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustPaperChunk>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_paper_chunk(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustChunkHit sse_decode_rust_chunk_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_row = sse_decode_rust_chunk_row(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    return RustChunkHit(row: var_row, score: var_score);
  }

  @protected
  RustChunkRow sse_decode_rust_chunk_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chunkId = sse_decode_String(deserializer);
    var var_docId = sse_decode_String(deserializer);
    var var_page = sse_decode_i_32(deserializer);
    var var_ordinal = sse_decode_i_32(deserializer);
    var var_section = sse_decode_String(deserializer);
    var var_startChar = sse_decode_i_32(deserializer);
    var var_endChar = sse_decode_i_32(deserializer);
    var var_text = sse_decode_String(deserializer);
    return RustChunkRow(
      chunkId: var_chunkId,
      docId: var_docId,
      page: var_page,
      ordinal: var_ordinal,
      section: var_section,
      startChar: var_startChar,
      endChar: var_endChar,
      text: var_text,
    );
  }

  @protected
  RustPaperChunk sse_decode_rust_paper_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_page = sse_decode_i_32(deserializer);
    var var_ordinal = sse_decode_i_32(deserializer);
    var var_section = sse_decode_String(deserializer);
    var var_startChar = sse_decode_i_32(deserializer);
    var var_endChar = sse_decode_i_32(deserializer);
    var var_text = sse_decode_String(deserializer);
    return RustPaperChunk(
      id: var_id,
      page: var_page,
      ordinal: var_ordinal,
      section: var_section,
      startChar: var_startChar,
      endChar: var_endChar,
      text: var_text,
    );
  }

  @protected
  RustPdfProcessedResult sse_decode_rust_pdf_processed_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_String(deserializer);
    var var_pageCount = sse_decode_i_32(deserializer);
    var var_chunks = sse_decode_list_rust_paper_chunk(deserializer);
    var var_emptyPages = sse_decode_list_prim_i_32_strict(deserializer);
    var var_pdfType = sse_decode_String(deserializer);
    var var_needsOcrPages = sse_decode_list_prim_i_32_strict(deserializer);
    return RustPdfProcessedResult(
      title: var_title,
      pageCount: var_pageCount,
      chunks: var_chunks,
      emptyPages: var_emptyPages,
      pdfType: var_pdfType,
      needsOcrPages: var_needsOcrPages,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
    NativeChunkStore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NativeChunkStoreImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
    NativeChunkStore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NativeChunkStoreImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_CastedPrimitive_usize(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeChunkStore(
    NativeChunkStore self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NativeChunkStoreImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rust_chunk_hit(
    List<RustChunkHit> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_chunk_hit(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_chunk_row(
    List<RustChunkRow> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_chunk_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_rust_paper_chunk(
    List<RustPaperChunk> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_paper_chunk(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_rust_chunk_hit(RustChunkHit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_rust_chunk_row(self.row, serializer);
    sse_encode_f_32(self.score, serializer);
  }

  @protected
  void sse_encode_rust_chunk_row(RustChunkRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.chunkId, serializer);
    sse_encode_String(self.docId, serializer);
    sse_encode_i_32(self.page, serializer);
    sse_encode_i_32(self.ordinal, serializer);
    sse_encode_String(self.section, serializer);
    sse_encode_i_32(self.startChar, serializer);
    sse_encode_i_32(self.endChar, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_rust_paper_chunk(
    RustPaperChunk self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_32(self.page, serializer);
    sse_encode_i_32(self.ordinal, serializer);
    sse_encode_String(self.section, serializer);
    sse_encode_i_32(self.startChar, serializer);
    sse_encode_i_32(self.endChar, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_rust_pdf_processed_result(
    RustPdfProcessedResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.title, serializer);
    sse_encode_i_32(self.pageCount, serializer);
    sse_encode_list_rust_paper_chunk(self.chunks, serializer);
    sse_encode_list_prim_i_32_strict(self.emptyPages, serializer);
    sse_encode_String(self.pdfType, serializer);
    sse_encode_list_prim_i_32_strict(self.needsOcrPages, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class NativeChunkStoreImpl extends RustOpaque implements NativeChunkStore {
  // Not to be used by end users
  NativeChunkStoreImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NativeChunkStoreImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_NativeChunkStore,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_NativeChunkStore,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_NativeChunkStorePtr,
  );

  /// Appends `rows` with their flattened `vectors` in a single transaction.
  Future<void> add({
    required List<RustChunkRow> rows,
    required List<double> vectors,
  }) => RustLib.instance.api.crateApiLanceStoreNativeChunkStoreAdd(
    that: this,
    rows: rows,
    vectors: vectors,
  );

  /// Compacts fragments and prunes superseded versions.
  ///
  /// Every append and delete creates a new dataset version, and Lance keeps
  /// them until told otherwise, so this runs after each import.
  Future<void> compact() => RustLib.instance.api
      .crateApiLanceStoreNativeChunkStoreCompact(that: this);

  Future<int> count() =>
      RustLib.instance.api.crateApiLanceStoreNativeChunkStoreCount(that: this);

  /// Removes every row belonging to one document.
  Future<void> deleteDoc({required String docId}) => RustLib.instance.api
      .crateApiLanceStoreNativeChunkStoreDeleteDoc(that: this, docId: docId);

  Future<int> dim() =>
      RustLib.instance.api.crateApiLanceStoreNativeChunkStoreDim(that: this);

  /// Distinct document ids currently in the table.
  Future<List<String>> docIds() =>
      RustLib.instance.api.crateApiLanceStoreNativeChunkStoreDocIds(that: this);

  /// Non-vector scan of one page of one document, ordered by chunk ordinal.
  Future<List<RustChunkRow>> pageChunks({
    required String docId,
    required int page,
    required int limit,
  }) => RustLib.instance.api.crateApiLanceStoreNativeChunkStorePageChunks(
    that: this,
    docId: docId,
    page: page,
    limit: limit,
  );

  /// Removes rows whose document is not in `doc_ids`, returning the number of
  /// documents dropped. This is the orphan sweep that replaces the old
  /// dirty/clean index-state protocol.
  ///
  /// Nothing is written when there is nothing stale — every write would
  /// otherwise append a dataset version on each app start.
  Future<int> retainDocs({required List<String> docIds}) => RustLib.instance.api
      .crateApiLanceStoreNativeChunkStoreRetainDocs(that: this, docIds: docIds);

  /// Exact cosine search. Embeddings are L2-normalized by the caller, so the
  /// returned score is the cosine similarity.
  Future<List<RustChunkHit>> search({
    required List<double> query,
    required int k,
  }) => RustLib.instance.api.crateApiLanceStoreNativeChunkStoreSearch(
    that: this,
    query: query,
    k: k,
  );
}
