// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/pdf_images.dart';
import 'api/vector_index.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1449220834;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'lab_05_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiVectorIndexNativeVectorIndexAddBatch({
    required NativeVectorIndex that,
    required List<int> ids,
    required List<double> vectors,
    required int dim,
  });

  Future<int> crateApiVectorIndexNativeVectorIndexDim({
    required NativeVectorIndex that,
  });

  Future<int> crateApiVectorIndexNativeVectorIndexLen({
    required NativeVectorIndex that,
  });

  Future<NativeVectorIndex> crateApiVectorIndexNativeVectorIndexLoad({
    required String path,
  });

  Future<NativeVectorIndex> crateApiVectorIndexNativeVectorIndexNew({
    required int dim,
    required int bitWidth,
  });

  Future<bool> crateApiVectorIndexNativeVectorIndexRemove({
    required NativeVectorIndex that,
    required int id,
  });

  Future<List<RustSearchResult>> crateApiVectorIndexNativeVectorIndexSearch({
    required NativeVectorIndex that,
    required List<double> query,
    required int k,
    List<int>? allowlist,
  });

  Future<void> crateApiVectorIndexNativeVectorIndexWrite({
    required NativeVectorIndex that,
    required String path,
  });

  Future<StrippedPdf> crateApiPdfImagesExtractAndStripImages({
    required String pdfPath,
    required int minWidth,
    required int minHeight,
  });

  Future<void> crateApiInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NativeVectorIndex;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NativeVectorIndex;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_NativeVectorIndexPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiVectorIndexNativeVectorIndexAddBatch({
    required NativeVectorIndex that,
    required List<int> ids,
    required List<double> vectors,
    required int dim,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
            that,
            serializer,
          );
          sse_encode_list_CastedPrimitive_u_64(ids, serializer);
          sse_encode_list_prim_f_32_loose(vectors, serializer);
          sse_encode_CastedPrimitive_usize(dim, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVectorIndexNativeVectorIndexAddBatchConstMeta,
        argValues: [that, ids, vectors, dim],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVectorIndexNativeVectorIndexAddBatchConstMeta =>
      const TaskConstMeta(
        debugName: "NativeVectorIndex_add_batch",
        argNames: ["that", "ids", "vectors", "dim"],
      );

  @override
  Future<int> crateApiVectorIndexNativeVectorIndexDim({
    required NativeVectorIndex that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_CastedPrimitive_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVectorIndexNativeVectorIndexDimConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVectorIndexNativeVectorIndexDimConstMeta =>
      const TaskConstMeta(
        debugName: "NativeVectorIndex_dim",
        argNames: ["that"],
      );

  @override
  Future<int> crateApiVectorIndexNativeVectorIndexLen({
    required NativeVectorIndex that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_CastedPrimitive_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVectorIndexNativeVectorIndexLenConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVectorIndexNativeVectorIndexLenConstMeta =>
      const TaskConstMeta(
        debugName: "NativeVectorIndex_len",
        argNames: ["that"],
      );

  @override
  Future<NativeVectorIndex> crateApiVectorIndexNativeVectorIndexLoad({
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVectorIndexNativeVectorIndexLoadConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVectorIndexNativeVectorIndexLoadConstMeta =>
      const TaskConstMeta(
        debugName: "NativeVectorIndex_load",
        argNames: ["path"],
      );

  @override
  Future<NativeVectorIndex> crateApiVectorIndexNativeVectorIndexNew({
    required int dim,
    required int bitWidth,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_CastedPrimitive_usize(dim, serializer);
          sse_encode_CastedPrimitive_usize(bitWidth, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVectorIndexNativeVectorIndexNewConstMeta,
        argValues: [dim, bitWidth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVectorIndexNativeVectorIndexNewConstMeta =>
      const TaskConstMeta(
        debugName: "NativeVectorIndex_new",
        argNames: ["dim", "bitWidth"],
      );

  @override
  Future<bool> crateApiVectorIndexNativeVectorIndexRemove({
    required NativeVectorIndex that,
    required int id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
            that,
            serializer,
          );
          sse_encode_CastedPrimitive_u_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVectorIndexNativeVectorIndexRemoveConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVectorIndexNativeVectorIndexRemoveConstMeta =>
      const TaskConstMeta(
        debugName: "NativeVectorIndex_remove",
        argNames: ["that", "id"],
      );

  @override
  Future<List<RustSearchResult>> crateApiVectorIndexNativeVectorIndexSearch({
    required NativeVectorIndex that,
    required List<double> query,
    required int k,
    List<int>? allowlist,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
            that,
            serializer,
          );
          sse_encode_list_prim_f_32_loose(query, serializer);
          sse_encode_CastedPrimitive_usize(k, serializer);
          sse_encode_opt_list_CastedPrimitive_u_64(allowlist, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rust_search_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVectorIndexNativeVectorIndexSearchConstMeta,
        argValues: [that, query, k, allowlist],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVectorIndexNativeVectorIndexSearchConstMeta =>
      const TaskConstMeta(
        debugName: "NativeVectorIndex_search",
        argNames: ["that", "query", "k", "allowlist"],
      );

  @override
  Future<void> crateApiVectorIndexNativeVectorIndexWrite({
    required NativeVectorIndex that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiVectorIndexNativeVectorIndexWriteConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVectorIndexNativeVectorIndexWriteConstMeta =>
      const TaskConstMeta(
        debugName: "NativeVectorIndex_write",
        argNames: ["that", "path"],
      );

  @override
  Future<StrippedPdf> crateApiPdfImagesExtractAndStripImages({
    required String pdfPath,
    required int minWidth,
    required int minHeight,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pdfPath, serializer);
          sse_encode_u_32(minWidth, serializer);
          sse_encode_u_32(minHeight, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stripped_pdf,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPdfImagesExtractAndStripImagesConstMeta,
        argValues: [pdfPath, minWidth, minHeight],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPdfImagesExtractAndStripImagesConstMeta =>
      const TaskConstMeta(
        debugName: "extract_and_strip_images",
        argNames: ["pdfPath", "minWidth", "minHeight"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_NativeVectorIndex => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_NativeVectorIndex => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex;

  @protected
  NativeVectorIndex
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativeVectorIndexImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  NativeVectorIndex
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativeVectorIndexImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  int dco_decode_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  int dco_decode_CastedPrimitive_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  NativeVectorIndex
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NativeVectorIndexImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ExtractedImage dco_decode_extracted_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ExtractedImage(
      page: dco_decode_u_32(arr[0]),
      indexOnPage: dco_decode_u_32(arr[1]),
      name: dco_decode_String(arr[2]),
      width: dco_decode_u_32(arr[3]),
      height: dco_decode_u_32(arr[4]),
      mediaType: dco_decode_String(arr[5]),
      bytes: dco_decode_list_prim_u_8_strict(arr[6]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<int> dco_decode_list_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_CastedPrimitive_u_64).toList();
  }

  @protected
  List<ExtractedImage> dco_decode_list_extracted_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_extracted_image).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RustSearchResult> dco_decode_list_rust_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_search_result).toList();
  }

  @protected
  List<int>? dco_decode_opt_list_CastedPrimitive_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_CastedPrimitive_u_64(raw);
  }

  @protected
  RustSearchResult dco_decode_rust_search_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustSearchResult(
      vectorId: dco_decode_CastedPrimitive_u_64(arr[0]),
      score: dco_decode_f_32(arr[1]),
    );
  }

  @protected
  StrippedPdf dco_decode_stripped_pdf(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return StrippedPdf(
      pdf: dco_decode_list_prim_u_8_strict(arr[0]),
      images: dco_decode_list_extracted_image(arr[1]),
      pageCount: dco_decode_u_32(arr[2]),
      originalBytes: dco_decode_CastedPrimitive_u_64(arr[3]),
      skipped: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  NativeVectorIndex
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NativeVectorIndexImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  NativeVectorIndex
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NativeVectorIndexImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  int sse_decode_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_u_64(deserializer);
    return inner.toInt();
  }

  @protected
  int sse_decode_CastedPrimitive_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_usize(deserializer);
    return inner.toInt();
  }

  @protected
  NativeVectorIndex
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return NativeVectorIndexImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ExtractedImage sse_decode_extracted_image(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_page = sse_decode_u_32(deserializer);
    var var_indexOnPage = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_mediaType = sse_decode_String(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    return ExtractedImage(
      page: var_page,
      indexOnPage: var_indexOnPage,
      name: var_name,
      width: var_width,
      height: var_height,
      mediaType: var_mediaType,
      bytes: var_bytes,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  List<int> sse_decode_list_CastedPrimitive_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <int>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_CastedPrimitive_u_64(deserializer));
    }
    return ans_;
  }

  @protected
  List<ExtractedImage> sse_decode_list_extracted_image(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ExtractedImage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_extracted_image(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RustSearchResult> sse_decode_list_rust_search_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustSearchResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_search_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<int>? sse_decode_opt_list_CastedPrimitive_u_64(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_CastedPrimitive_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustSearchResult sse_decode_rust_search_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_vectorId = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    return RustSearchResult(vectorId: var_vectorId, score: var_score);
  }

  @protected
  StrippedPdf sse_decode_stripped_pdf(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pdf = sse_decode_list_prim_u_8_strict(deserializer);
    var var_images = sse_decode_list_extracted_image(deserializer);
    var var_pageCount = sse_decode_u_32(deserializer);
    var var_originalBytes = sse_decode_CastedPrimitive_u_64(deserializer);
    var var_skipped = sse_decode_u_32(deserializer);
    return StrippedPdf(
      pdf: var_pdf,
      images: var_images,
      pageCount: var_pageCount,
      originalBytes: var_originalBytes,
      skipped: var_skipped,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
    NativeVectorIndex self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NativeVectorIndexImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
    NativeVectorIndex self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NativeVectorIndexImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void sse_encode_CastedPrimitive_u_64(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void sse_encode_CastedPrimitive_usize(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerNativeVectorIndex(
    NativeVectorIndex self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as NativeVectorIndexImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_extracted_image(
    ExtractedImage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.page, serializer);
    sse_encode_u_32(self.indexOnPage, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_String(self.mediaType, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_list_CastedPrimitive_u_64(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_CastedPrimitive_u_64(item, serializer);
    }
  }

  @protected
  void sse_encode_list_extracted_image(
    List<ExtractedImage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_extracted_image(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rust_search_result(
    List<RustSearchResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_search_result(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_CastedPrimitive_u_64(
    List<int>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_CastedPrimitive_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_rust_search_result(
    RustSearchResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_CastedPrimitive_u_64(self.vectorId, serializer);
    sse_encode_f_32(self.score, serializer);
  }

  @protected
  void sse_encode_stripped_pdf(StrippedPdf self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.pdf, serializer);
    sse_encode_list_extracted_image(self.images, serializer);
    sse_encode_u_32(self.pageCount, serializer);
    sse_encode_CastedPrimitive_u_64(self.originalBytes, serializer);
    sse_encode_u_32(self.skipped, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class NativeVectorIndexImpl extends RustOpaque implements NativeVectorIndex {
  // Not to be used by end users
  NativeVectorIndexImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  NativeVectorIndexImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_NativeVectorIndex,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_NativeVectorIndex,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_NativeVectorIndexPtr,
  );

  Future<void> addBatch({
    required List<int> ids,
    required List<double> vectors,
    required int dim,
  }) => RustLib.instance.api.crateApiVectorIndexNativeVectorIndexAddBatch(
    that: this,
    ids: ids,
    vectors: vectors,
    dim: dim,
  );

  Future<int> dim() =>
      RustLib.instance.api.crateApiVectorIndexNativeVectorIndexDim(that: this);

  Future<int> len() =>
      RustLib.instance.api.crateApiVectorIndexNativeVectorIndexLen(that: this);

  Future<bool> remove({required int id}) => RustLib.instance.api
      .crateApiVectorIndexNativeVectorIndexRemove(that: this, id: id);

  Future<List<RustSearchResult>> search({
    required List<double> query,
    required int k,
    List<int>? allowlist,
  }) => RustLib.instance.api.crateApiVectorIndexNativeVectorIndexSearch(
    that: this,
    query: query,
    k: k,
    allowlist: allowlist,
  );

  Future<void> write({required String path}) => RustLib.instance.api
      .crateApiVectorIndexNativeVectorIndexWrite(that: this, path: path);
}
